# Generated by Django 5.0.2 on 2024-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('perishable', 'Perishable'), ('non-perishable', 'Non-Perishable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='fix_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='km_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
